### ISSUE TITLE
Could be cool to set the speed to show in KM/h

### ISSUE THREAD

**Issue by diamkil** [zackdevine/FH4RP#1]

**Comment by jaaiden** [comment]
I'll definitely look to add some sort of configuration file and add this as an option!

**Comment by adx74** [comment]
The option has been added ?

**Comment by jaaiden** [comment]
The option has been added to the `add-kmh-config` branch, but I haven't been able to fully test it yet. I don't have a lot of free time nowadays so if someone could test it for me, that would be great 😄

**Comment by diamkil** [comment]
> The option has been added to the `add-kmh-config` branch, but I haven't been able to fully test it yet. I don't have a lot of free time nowadays so if someone could test it for me, that would be great 😄

Will be trying out!

**Comment by diamkil** [comment]
> The option has been added to the `add-kmh-config` branch, but I haven't been able to fully test it yet. I don't have a lot of free time nowadays so if someone could test it for me, that would be great 😄

can you give me instructions on the command to compile it?

**Comment by jaaiden** [comment]
Install Visual Studio 2019 (Community is fine) with the .NET Core package (this project targets .NET Core 2.2, you might need to enable it under individual components in the VS Installer), clone the branch and open it up via the .sln file.

On the first run it should generate a config file (`config.json`) with some default values. This config file is where you enable the KMH option (disabled by default).

When I get a chance I'll make sure to add more in-depth instructions, but these should be good for now 😅

**Comment by diamkil** [comment]
> Install Visual Studio 2019 (Community is fine) with the .NET Core package (this project targets .NET Core 2.2, you might need to enable it under individual components in the VS Installer), clone the branch and open it up via the .sln file.
> 
> On the first run it should generate a config file (`config.json`) with some default values. This config file is where you enable the KMH option (disabled by default).
> 
> When I get a chance I'll make sure to add more in-depth instructions, but these should be good for now 😅

The config.json file doesn't seem to get created https://i.dkil.ca/20200713173457.png https://i.dkil.ca/20200713173527.png

**Comment by jaaiden** [comment]
It looks like you're on the master branch of the repository. Try cloning the [add-kmh-config](https://github.com/zackdevine/FH4RP/tree/add-kmh-config) branch and see if that works for you!

**Comment by diamkil** [comment]
> It looks like you're on the master branch of the repository. Try cloning the [add-kmh-config](https://github.com/zackdevine/FH4RP/tree/add-kmh-config) branch and see if that works for you!

realised I had forgot to specify the branch in my git clone 😅

**Comment by diamkil** [comment]
so it works perfectly so far, I changed kph to km/h in the TelemetryData.cs file
line 356 `? $"{GetKPH()} kph"` to `? $"{GetKPH()} km/h"`
but it wouldn't allow me to git push
