### ISSUE TITLE
Remove Car

### ISSUE THREAD

**Issue by PiSaucer** [zackdevine/FH4RP#2]
I accidentally added car with the wrong id on [forzadb.dgtl.dev](forzadb.dgtl.dev). Is there a way to remove cars with wrong information?

**Comment by jaaiden** [comment]
The website was extremely rushed when I made it, and it definitely needs a rewrite... 😅

There's no current way of modifying/deleting entries to the database, but I do plan on doing that rewrite (hopefully!) soon and I'll definitely have that ability in the new version. In the meantime I can go in to the database and manually adjust the info for you!

**Comment by PiSaucer** [comment]
Can you please remove this one [forzadb.dgtl.dev/vehicles/2472](https://forzadb.dgtl.dev/vehicles/2472)?

**Comment by jaaiden** [comment]
All set!
