### ISSUE TITLE
Issue with Steam version

### ISSUE THREAD

**Issue by byzocker** [zackdevine/FH4RP#3]
since the steam version isnt uwp i cant use the command and it just closes the second I launch it

**Comment by jaaiden** [comment]
The CheckNetIsolation command is only for the UWP (MS Store) version of the game, so you shouldn't need to run it at all! I don't have the Steam version myself so I can't test it, but just running the FH4RP executable should be enough!

**Comment by byzocker** [comment]
the executable doesnt open at all though

is it maybe cuz I'm on windows 11?

**Comment by jaaiden** [comment]
It could be, I've only tested this on Windows 10. I'll load up a Win11 VM and try it out.

**Comment by jaaiden** [comment]
It looks like it's working for me perfectly fine. Did you make sure to extract everything from the latest release zip? The program requires all of those files to run properly.

**Comment by byzocker** [comment]
Yes, it opens for a split second but it closes instantly

maybe because hyperv? i have no idea

**Comment by Bobu5** [comment]
> It looks like it's working for me perfectly fine. Did you make sure to extract everything from the latest release zip? The program requires all of those files to run properly.

can vouch this, also works fine for me

**Comment by jaaiden** [comment]
I meant to come back to this issue, sorry! Yeah I'm not sure what else would cause it to not work other than some/all of the necessary DLLs being missing from the application directory. Having Hyper-V enabled shouldn't cause any issues with running .NET console apps (if it did then we'd have bigger problems!)

Another reason why the program wouldn't work is if you don't have Discord installed locally on the same computer you're running FH4RP on. (Running just the browser app wouldn't work - FH4RP uses a library that directly interfaces with the Discord application to show rich presence data)

**Comment by byzocker** [comment]
its been a long time ima close this now
