### ISSUE TITLE
compatible with forza horizon 5?

### ISSUE THREAD

**Issue by Electronic-Idiot** [zackdevine/FH4RP#4]

**Comment by jaaiden** [comment]
From my quick testing, yes this program is compatible with Horizon 5 (I have only tested with the Steam version, as that is what I own). I'm unsure if the MS Store version requires a command to be run to allow for local connections like Horizon 4 does.

I do have some other ideas in mind for Horizon 5 though, so be sure to check out [FH5RP](https://github.com/jaiden-d/FH5RP) once I get some development done on it!

**Comment by Electronic-Idiot** [comment]
Thanks , appreciate the effort
